name: Build, Release with SHA256 and Upload Homebrew Tap

on:
  release:
    types: [created]

jobs:
  build_and_hash_and_upload_tap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create tar.gz package
      run: |
        # 假设你发布的是整个 repo 根目录压缩包
        tar czf rm-trash-${{ github.ref_name }}.tar.gz bin package.json

    - name: Compute SHA256 hash
      run: |
        sha256sum rm-trash-${{ github.ref_name }}.tar.gz > rm-trash-${{ github.ref_name }}.tar.gz.sha256
        HASH=$(cut -d ' ' -f1 rm-trash-${{ github.ref_name }}.tar.gz.sha256)
        echo "SHA256=$HASH" >> $GITHUB_ENV

    - name: Upload Release Asset - tar.gz
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rm-trash-${{ github.ref_name }}.tar.gz
          rm-trash-${{ github.ref_name }}.tar.gz.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Homebrew Tap repo
      uses: actions/checkout@v3
      with:
        repository: hotoo/homebrew-tap
        token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        path: homebrew-tap

    - name: Update Homebrew formula SHA256 and url
      run: |
        FORMULA_PATH=homebrew-tap/Formula/rm-trash.rb
        echo "Updating SHA256 in $FORMULA_PATH"
        # 使用 sed 替换 sha256 行，假设格式形如: sha256 "oldhash"
        sed -i "s/sha256 \".*\"/sha256 \"${SHA256}\"/" "$FORMULA_PATH"
        echo "Updating url in $FORMULA_PATH"
        sed -i "s/url \".*\"/url \"https:\/\/github.com\/hotoo\/rm-trash\/releases\/download\/${{ github.ref_name }}\/rm-trash-${{ github.ref_name }}.tar.gz\"/" "$FORMULA_PATH"

    - name: Commit and push changes
      run: |
        cd homebrew-tap
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Formula/rm-trash.rb
        git commit -m "Update rm-trash sha256 for ${{ github.ref_name }}"
        git push origin main